blog/urls.py
from django.conf.urls import url
from blog.views import BlogListView, BlogDetailView, BlogUpdateView, BlogCreateView, BlogDeleteView, GameListView, GameDetailView

urlpatterns = [
    url(r'^$', BlogListView.as_view(), name='bloglist'),
    url(r'^(?P<pk>\d+)/$', BlogDetailView.as_view(), name='blogdetail'),
    url(r'^(?P<pk>\d+)/update/$', BlogUpdateView.as_view(), name='blogupdate'),
    url(r'^new$', BlogCreateView.as_view(), name='blogcreate'),
    url(r'^(?P<pk>\d+)/delete$', BlogDeleteView.as_view(), name='blogdelete'),

    url(r'^$', GameListView.as_view(), name='gamelist'),
    url(r'^detail/$', GameDetailView.as_view(), name='gamedetail'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import HomeView, myGamePlay

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^ajax/mygame/detail/', myGamePlay, name='ajaxmygameplay')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.

class BlogPost(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=50)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date =models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('blog:blogdetail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    def publish(self):
        self.published_date = timezone.now()
        self.save()


class GamePlay(models.Model):
    LEFT = 'LT'
    RIGHT = 'RT'
    LEFTRIGHT_CHOICES = (
        (LEFT, '왼쪽'),
        (RIGHT, '오른쪽')
    )
    leftright = models.CharField(max_length=2, choices=LEFTRIGHT_CHOICES)
    usr = models.ForeignKey('auth.User')
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.leftright

blog/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.base import TemplateView
from blog.models import BlogPost, GamePlay
from django.urls import reverse_lazy
# Create your views here.

class BlogListView(ListView):
    model = BlogPost

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['play'] = GamePlay.objects.all()
        return context


class BlogDetailView(DetailView):
    model = BlogPost


class BlogUpdateView(UpdateView):
    model = BlogPost
    fields = ['author', 'title', 'text', 'created_date', 'published_date']
    template_name_suffix = '_update_form'


class BlogCreateView(CreateView):
    model = BlogPost
    fields = ['author', 'title', 'text', 'created_date', 'published_date']


class BlogDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blog:bloglist')


class GameListView(ListView):
    model = GamePlay


class GameDetailView(TemplateView):
    template_name = 'blog/game_detail.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        count_lt = GamePlay.objects.filter(usr=user, leftright="LT").count()
        count_rt = GamePlay.objects.filter(usr=user, leftright="RT").count()
        last_login = GamePlay.objects.filter(usr=user).order_by("-created_date")[0]
        context = super().get_context_data(**kwargs)
        context['user_id'] = user
        context['count_lt'] = count_lt
        context['count_rt'] = count_rt
        context['last_login'] = last_login
        return context

mysite/views.py
from django.views.generic.base import TemplateView
from blog.models import GamePlay
from django.http import JsonResponse

class HomeView(TemplateView):
    template_name = 'home.html'


def myGamePlay(request):
    user = request.user
    myDir = request.GET['dir']
    GamePlay.objects.create(usr=user, leftright=myDir)
    mycount = GamePlay.objects.filter(usr=user, leftright=myDir).count()
    result = {'myDir':myDir, 'mycount':mycount}
    return JsonResponse(result)

blog/templates/blog/base.html
{% extends 'home.html' %}

<h1>블로그입니다.</h1>

{% block title %}
{% endblock %}

{% block sub_content %}
{% endblock %}

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'blog/base.html' %}

{% block title %}
<a href="{% url 'blog:blogdetail' object.pk %}">{{ object }}</a>로 바로가기
{% endblock %}

{% block sub_content %}
<form action="" method="post">
    {% csrf_token %}
    <p>{{ object }}을(를) 정말 삭제하시겠습니까?</p>
    <input type="submit" value="옛썰!" />
</form>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'blog/base.html' %}

{% block sub_content %}

<h1>{{ object }}</h1>
<p><a href="{% url 'blog:blogupdate' object.pk %}">수정하기</a></p>
<p><a href="{% url 'blog:blogdelete' object.pk %}">삭제하기</a></p>
{{ object.text }}

{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'blog/base.html' %}

{% block title %}새글쓰기{% endblock %}

{% block sub_content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="새글쓰기" />
</form>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'blog/base.html' %}

{% block sub_content %}

<div>
    <h1>블러그</h1>
    <ul>
        {% for obj in object_list %}
        <li><a href="{% url 'blog:blogdetail' obj.pk %}">{{ obj }}</a></li>
        {% endfor %}
    </ul>
</div>

<div>
    <h2>왼쪽 오른쪽 게임</h2>
    <p>게임 현황</p>
    <ul>
        {% for ob in play %}
        <li>"{{ ob.usr }}"님, {{ ob.created_date }}, {{ ob.leftright }}</li>
        {% empty %}
        <li>게임 참여 내역이 없습니다. 게임을 참여해 보세요^^*</li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

blog/templates/blog/blogpost_update_form.html
{% extends 'blog/base.html' %}

{% block title %}
<p><a href="{% url 'blog:blogdetail' object.pk %}">{{ object }}</a>로 바로가기</p>
{% endblock %}

{% block sub_content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정" />
</form>
{% endblock %}

blog/templates/blog/game_detail.html
{% extends 'blog/base.html' %}

{% block title %}
<h1>게임 참여중...</h1>
{% endblock %}

{% block sub_content %}
<div>
    <h2>"{{ user_id }}"님이 게임을 시작하였습니다.</h2>
    <table>
        <tr>
            <th>좌</th>
            <th>우</th>
        </tr>
        <tr>
            <td>{{ count_lt }}</td>
            <td>{{ count_rt }}</td>
        </tr>
        <tr>
            <td><a href=""><button type="button" onclick="myGamePlay('LT')">왼쪽</button></a></td>
            <td><a href=""><button type="button" onclick="myGamePlay('RT')">오른쪽</button></a></td>
        </tr>
    </table>
    <p>버튼을 클릭하면 1씩 증가합니다.</p>
    <p>오늘 하루도 열심히 클릭해보세요~</p>
    <p>마지막 참여:{{ last_login.created_date }}</p>
</div>

<script>
    function myGamePlay(para) {
        var elem_lt = document.getElementById('count_lt');
        var elem_rt = document.getElementById('count_rt');
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                var obj = JSON.parse(this.responseText);
                if (obj.myDir == 'LT') {
                    elem_lt.textContext = obj.myCount
                } else if (obj.myDir == 'RT') {
                    elem_rt.textContext = obj.myCount
                }
            }
        };
        xhttp.open("GET", "{% url 'ajaxmygameplay' %}?dir="+para, true);
        xhttp.send()
    }
</script>
{% endblock %}

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav>
    <a href="{% url 'home' %}">홈으로가기</a>
    <a href="{% url 'blog:bloglist' %}">글보기</a>
    <a href="{% url 'blog:blogcreate' %}">새글쓰기</a>
    <a href="{% url 'blog:gamedetail' %}">왼쪽 오른쪽</a>
</nav>


<h1>{% block title %}{% endblock %}</h1>

{% block sub_content %}{% endblock %}

</body>
</html>